# Generated by Django 4.2.1 on 2024-10-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_customer_data_exp_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_data",
            name="dueMoney",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="customer_data",
            name="givenMoney",
            field=models.FloatField(default=0.0),
        ),
    ]
