# Generated by Django 4.2.1 on 2024-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_duemoney_customer_data_totalmoney"),
    ]

    operations = [
        migrations.CreateModel(
            name="deletedCustemers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("location", models.TextField(null=True)),
                ("mobileNumber", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
