# Generated by Django 4.2.1 on 2024-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_deletedcustemers_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="leaveDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
            ],
        ),
    ]
